Add `apply_chat_template` to Tokenizer
outlines-dev/outlines pull request #1073
Opened 2024-07-29 20:53 UTC by leloykun

This PR adds `apply_chat_template` to Outline's `Tokenizer`

## Usage:

###

Unlike Huggingface's tokenizers, we can directly pass the text prompt to `tokenizer.apply_chat_template`. This will first convert the prompt into conversation format with a predefined system message, then applies the chat template to the result.

```python
answer = generator(
    tokenizer.apply_chat_template(prompt)
)
```

To use a different system message, either (1) modify `tokenizer.SYSTEM_MESSAGE["content"]` or (2) build the conversation yourself then pass it to the `apply_chat_template` here:

```
conversation = [
    {
        "role": "system",
        "content": "You are a helpful assistant. Please do not say swear words.",
    },
    {
        "role": "user",
        "content": [insert prompt here],
    },
]
```

```python
answer = generator(
    tokenizer.apply_chat_template(conversation)
)
```

## Interface changes:

Default behavior is kept as is.

-----------

@rlouf @lapp0 imo adding it to the tokenizer instead of the model makes more sense.

* in chatml format

2024-07-29 21:21 UTC, lapp0 requested changes
Good progress!

Could you please address my comments and
- add unit tests
- add integration tests which simply verify the method runs successfully and introduces a `bos` token in the result with different popular models tokenizers?

2024-07-29 21:21 UTC, lapp0 commented on outlines/models/llamacpp.py
> +        raise NotImplementedError("Chat templates are not yet supported by llama-cpp")
Could you either say "not yet supported by Outlines llama-cpp integration" or implement https://github.com/abetlen/llama-cpp-python/blob/master/README.md#chat-completion

2024-07-29 21:21 UTC, lapp0 commented on outlines/models/transformers.py
> +        self.ASSISTANT_MESSAGE_TEMPLATE = lambda x: {"role": "assistant", "content": x}
this is never used

2024-07-29 21:21 UTC, lapp0 commented on outlines/models/transformers.py
> +        )
Not all models have a system message (e.g. phi-3)

Is there a way built into `transformers` to handle this? (I'm not aware of one)

2024-07-30 09:59 UTC, rlouf commented
I think these changes should be applied to the [new `prompts` library](https://github.com/outlines-dev/prompts).

2024-08-12 11:44 UTC, rlouf commented
Closing in favor of `outlines-dev/prompts`

2024-08-12 11:44 UTC, closed without merging