support the recursive array when the item is still a array
outlines-dev/outlines pull request #316
Opened 2023-10-10 09:58 UTC by AL-377

I have noticed that the origin outlines doesn't support recursive array type. To be clear, here is a example：

```python
from outlines.text.json_schema import build_regex_from_schema
from pydantic import BaseModel
from typing import List
import json 

class ItemModel(BaseModel):
    name:str

class ArrayModel(BaseModel):
    items:List[List[int]]

test_json = \
{
    "items": [[{"name":"item1"},{"name":"item2"}]], 
}

json_schema = ArrayModel.model_json_schema()
print(json.dumps(json_schema,indent=2))

regex = build_regex_from_schema(json.dumps(json_schema))
print(regex)

parsed = ArrayModel.model_validate_json(json.dumps(test_json))
print(parsed)

```

Run the code above, then we can get the json schema of  `ArrayModel` , but we will get a error from `build_regex_from_schema` when we meet the `List[List[]]` type property.

And now, I have modified the code in outlines and it works. You can run the `test.py` to verify!

2023-10-10 14:59 UTC, brandonwillard requested changes

2023-10-10 14:59 UTC, brandonwillard commented on .DS_Store
Looks like this file was accidentally added.

2023-10-10 14:59 UTC, brandonwillard commented on test.py
These tests need to be added to the existing test files in `pytest` format.

2023-10-10 16:17 UTC, AL-377 commented on .DS_Store
OK，I have delete that file

2023-10-11 00:57 UTC, AL-377 commented on test.py
Sorry I have missed the pre-commit step before, and now it's done

2023-10-13 14:03 UTC, AL-377 commented
It is strange that the pytest here seems to fail in`test_continuation.py`, I have passed the `test_continuation.py` in my local machine.

<img width="1343" alt="image" src="https://github.com/outlines-dev/outlines/assets/57025632/80c02e6e-ce74-4d5f-8701-51a35231852d">

2023-10-13 15:40 UTC, AL-377 reviewed
The changes have done

2023-10-19 22:19 UTC, brandonwillard approved these changes

2023-10-19 22:20 UTC, brandonwillard commented
@AL-377, this was a great fix/enhancement; much appreciated!  I've added some minor refactoring and it should be ready to merge once everything finishes in CI.

2023-10-19 22:26 UTC, merged

2023-10-20 00:20 UTC, AL-377 commented
> @AL-377, this was a great fix/enhancement; much appreciated! I've added some minor refactoring and it should be ready to merge once everything finishes in CI.

👍👍👍

2023-10-20 00:21 UTC, AL-377 commented
> Thank you for the contribution and sorry for the delay in reviewing. Will get to it soon.

Never mind！